services:
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - remix
      - fastapi
    restart: unless-stopped

  remix:
    container_name: remix-container
    build: ./docker/remix
    # ポート公開を削除（Nginxを通じてアクセス）
    volumes:
      - ./docker/remix/app:/usr/server/app
      - ./docker/remix/public:/usr/server/public
      - ./docker/remix/exams:/usr/server/exams
      - ./docker/remix/prisma:/usr/server/prisma
      - ./docker/remix/utils:/usr/server/utils
      - ./docker/remix/create-admin.sql:/usr/server/create-admin.sql
      - ./docker/remix/fix-users.sql:/usr/server/fix-users.sql
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:p0ssw0rd@db:3306/psyexam
      - SESSION_SECRET=your-super-secret-key-here
      - NODE_ENV=development
      - DEBUG=express:*
      - REMIX_DEV_SERVER_WS_PORT=3010
      - FASTAPI_URL=/api  # 相対パスに変更
    restart: unless-stopped
  
  fastapi:
    container_name: fastapi-container
    build: ./fastapi
    # ポート公開を削除（Nginxを通じてアクセス）
    volumes:
      - ./fastapi/app:/app/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:p0ssw0rd@db:3306/psyexam
    restart: unless-stopped

  db:
    container_name: mysql-container
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: psyexam
      MYSQL_USER: sirsoldano
      MYSQL_PASSWORD: p0ssw0rd
      MYSQL_ROOT_PASSWORD: p0ssw0rd
      TZ: 'Asia/Tokyo'
    restart: unless-stopped
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3316:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pp0ssw0rd"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=p0ssw0rd
      - UPLOAD_LIMIT=128M
    ports:
      - 8090:80
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped